data:
  name: 'HyperElastic_Mesoscale'
  datapath: '../data/mesoscale_grid/tension_shear/train_N1000_s128.mat'
  offset: 0
  n_sample: 1000
  nx: 128
  sub: 1

prop:
  bulk_mean: 1750
  shear_mean: 328.125
  bulk_height: 525
  shear_height: 98.4375

model:
  layers: [64, 64, 64, 64]
  modes1: [20, 20, 20]
  modes2: [20, 20, 20]
  fc_dim: 128
  activation: gelu

train:
  batchsize: 128
  epochs: 100
  milestones: [50,100, 150, 200]
  base_lr: 0.001
  scheduler_gamma: 0.5
  f_loss: 1.0
  save_dir: 'mesoscale/different_F'
  save_name: 'tension_shear'

others:
  project: 'HyperElastic-Mesoscale'
  group: 'gelu-pino'
